spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todolist
    username: postgres
    password: Barsik123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081