spring:
  application:
    name: eureka-client
  datasource:
    url: jdbc:postgresql://localhost:5432/todolist
    username: postgres
    password: Barsik123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8764
eureka:
  client:
    eureka-server-port: 8761
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
  instance:
    preferIpAddress: true


