spring:
  application:
    name: gateway
server:
  port: 9001
eureka:
  client:
    eureka-server-port: 8761
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
  instance:
    preferIpAddress: true

