spring:
  application:
    name: auth-service
  #  main:
  #    web-application-type: reactive
  datasource:
    url: jdbc:postgresql://localhost:5432/todolist
    username: postgres
    password: Barsik123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 9000
eureka:
  client:
    eureka-server-port: 8761
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
  instance:
    preferIpAddress: true